#!/usr/bin/env python

import sys, time, os, getpass
from daemon import Daemon


repo_users = dict()
pending_users = dict()
repo_groups = dict()

class MyDaemon(Daemon):
        def run(self):
                while True:
                        time.sleep(1)

if __name__ == "__main__":
        daemon = MyDaemon('/tmp/daemon-example.pid')
        if len(sys.argv) == 2:
                if 'start' == sys.argv[1]:
                        daemon.start()
                elif 'stop' == sys.argv[1]:
                        daemon.stop()
                elif 'restart' == sys.argv[1]:
                        daemon.restart()
                elif 'share' == sys.argv[1]:
                        
                elif 'adduser' == sys.argv[1]:
                        
                elif 'retrieve' == sys.argv[1]:
                        
                elif 'add' == sys.argv[1]:
                        if(sys.argv[2] == '-m'):
                            filename = sys.argv[3]
                            message = sys.argv[4]
                            username = sys.argv[5]
                        else:
                            filename = sys.argv[2]
                            message = 'added changes to ' + filename
                            username = sys.arg[3]
                        message = username + ": " + message
                        os.system('git add ' + filename)
                        os.system('git commit -m ' + '\'' + message + '\'')

                elif 'push' == sys.argv[1]:
                        os.system('git push -u origin master')
                elif 'addpush' == sys.argv[1]:
                        
                elif 'addpushall' == sys.argv[1]:
                         
                else:
                        print "Unknown command"
                        sys.exit(2)
                sys.exit(0)
        else:
                print "usage: %s start|stop|restart" % sys.argv[0]
                sys.exit(2)
